version = "0.1"
name = "Synapse configuration panel"

[synapse_config]
name = "Synapse configuration"

    [synapse_config.server_config]
    name = "Synapse server configuration"

        [synapse_config.server_config.server_statistics]
        ask = "Server statistics"
        type = "boolean"
        default = false
        help = "True to send anonymous statistics about synapse to improve the performances"

        [synapse_config.server_config.is_free_registration]
        ask = "Server with free registration"
        type = "boolean"
        default = false
        help = "A public server means that anybody will be able to register on this server."

        [synapse_config.server_config.allow_public_rooms]
        ask = "Public rooms directory"
        type = "boolean"
        default = false
        help = "If set to 'false', requires authentication to access the server's public rooms directory through the client API and forbids any other homeserver to fetch the server's public rooms directory via federation."

    [synapse_config.client_config]
    name = "Matrix client configuration"

        [synapse_config.client_config.jitsi_server]
        ask = "Jitsi server address for conference"
        type = "string"
        default = 'jitsi.riot.im'
        help = "Address of the Jitsi server for conference. Note that it's only for conference in rooms with more than 2 person. With 2 person the stun/turn server is used."
        
        [synapse_config.client_config.e2e_enabled_by_default]
        ask = "End to end encryption by default for direct messages"
        type = "boolean"
        default = true
        help = "By default, Element will create encrypted DM rooms if the user you are chatting with has keys uploaded on their account. For private room creation, Element will default to encryption on but give you can disable this settings here."

[package_config]
name = "Package configuration"

    [package_config.package_config]
    name = "Upgrade"

        [package_config.package_config.backup_before_upgrade]
        ask = "Backup before upgrade"
        type = "boolean"
        default = true
        help = "True to do a backup before every upgrade"
